name = "All of Create - Aeronautics"
version = "v2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37f41bce69f45c8670d0b9399c881d19a76d0275401810aae9b4f5259dd4888f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
