name = "All of Create - Aeronautics"
version = "v2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6f713a69ff45b667d6a4c6a2bf83e9243bf117796c79aef74de84199e7755e0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
