name = "All of Create - Aeronautics"
version = "v2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "add2793536499820adcf7cceb284e7cfe46926f4be8facb2f2dc2389fc553503"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
